<link rel="stylesheet" type="text/css" media="screen" href="css/all.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/index.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/contact.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/footer.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/how-it-works.css">