<section id="aboutomarket">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div img-container>
                    <img src="./assets/DA/about-resize.png" class="img-fluid" alt="illustration about">
                </div>
            </div>
            <div class="col-lg-6">
                <div>
                <h2>About <span class="highlight">OMarket</span></h2>
                    <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Laborum minima ullam esse quos illo dolore consectetur perferendis,
                    minus, quasi animi odio officiis numquam necessitatibus officia adipisci 
                    repudiandae, ducimus rerum ea.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>