<div id="article_card">

    <div class="card" style="width: 18rem;">

    <img src="assets/DA/aboutpicture.png" class="card-img-top" alt="article_name_picture">
        <div class="card-body">

            <h5 class="card-title">Article Name</h5>
            <p class="card-text">10$/Month</p>
            <a href="#" class="btn btn-primary buttonView">View Detail</a>
            <a href="#" class="btn btn-primary buttonAdd">Add to Cart</a>
        </div>
    </div>
</div>