<section id="FAQ">
    <div class="container">
        <div class="row">
            <div class="border mb-3">
                <h2>FAQ</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="border mb-3">
                    Questions
                </div>
            </div>
        </div>
    </div>
</section>