<section id="FAQ" style="margin-bottom: 100px;">
    <div class="container">
        <div class="row">
            <h2 class="title">FAQ</h2>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="justify-content-center" style="border: unset !important;">
                    <div class="accordion" id="accordionExample" style="border: unset !important;">
                        <div class="card" style="background: transparent !important;
  border: unset !important;
">
                            <div class="card-header" id="headingOne" style="display: flex;border-bottom: 3px solid black;background: transparent;">
                                <h2 class="mb-0" style="width: 100%;">
                                    <button  style="text-transform: uppercase;color: black;font-weight: 700;" class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseThree">
                                        Collapsible Group Item
                                    </button>

                                </h2>
                                <h2>
                                    <i class="fa-solid fa-chevron-down"></i>
                                </h2>
                            </div>

                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                            <div class="card-body">
                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                            </div>
                            </div>
                        </div>
                        <div class="card" style="background: transparent !important;border: unset !important;">
                            <div class="card-header" id="headingTwo" style="display: flex;border-bottom: 3px solid black;background: transparent;">
                                <h2 class="mb-0" style="width: 100%;">
                                    <button  style="text-transform: uppercase;color: black;font-weight: 700;" class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseThree">
                                        Collapsible Group Item
                                    </button>

                                </h2>
                                <h2>
                                    <i class="fa-solid fa-chevron-down"></i>
                                </h2>
                            </div>
                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                            <div class="card-body">
                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                            </div>
                            </div>
                        </div>

                        <div class="card" style="background: transparent !important;border: unset !important;">
                            <div class="card-header" id="headingThree" style="display: flex;border-bottom: 3px solid black;background: transparent;">
                                <h2 class="mb-0" style="width: 100%;">
                                    <button  style="text-transform: uppercase;color: black;font-weight: 700;" class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    Collapsible Group Item
                                    </button>

                                </h2>
                                <h2>
                                    <i class="fa-solid fa-chevron-down"></i>
                                </h2>
                            </div>
                            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                                <div class="card-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                </div>
                            </div>
                        </div>

                        <div class="card" style="background: transparent !important;border: unset !important;">
                            <div class="card-header" id="headingFour" style="display: flex;border-bottom: 3px solid black;background: transparent;">
                                <h2 class="mb-0" style="width: 100%;">
                                    <button  style="text-transform: uppercase;color: black;font-weight: 700;" class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
                                        Collapsible Group Item
                                    </button>

                                </h2>
                                <h2>
                                    <i class="fa-solid fa-chevron-down"></i>
                                </h2>
                            </div>
                            <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                                <div class="card-body">
                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>