<section id="howitworks">
    <div class="container">
        <h2>HOW IT WORKS</h2>              
        <div class="row d-flex justify-content-between">
            <div class="col-lg-3 card"><!-- faites votre test -->
                <div>
                    <div class="row">
                        <div>
                            <div class="icon-container">
                                <i class="fa-solid fa-list"></i>
                            </div>
                            <div class="blackpipe"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <h4>1. Do your test</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 card"><!-- une recommandation de vos produits -->
                <div>
                <div class="row">
                        <div>
                            <div class="icon-container">
                                <i class="fa-solid fa-filter"></i>
                            </div>
                            <div class="blackpipe"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <h4>2. A recommendation of your products</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 card"><!-- payer de manière sécurisée -->
                <div>
                <div class="row">
                        <div>
                            <div class="icon-container">
                                <i class="fa-solid fa-credit-card"></i>
                            </div>
                            <div class="blackpipe"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <h4>3. Secure payment</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center button-container">
            <div class="colspan-6">
                <button>Take the Test</button>
            </div>
        </div>
    </div>    
</section>