<section>
    <div class="container">
        <h2>HOW IT WORKS</h2>              
        <div class="row">
            <div class="col-lg-4">
                <div class="border mb-3">
                    <div class="row">
                        <div class="border mb-3">re</div>
                    </div>
                    <div class="row">
                        <div class="border mb-3">re</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="border mb-3">
                <div class="row">
                        <div class="border mb-3">re</div>
                    </div>
                    <div class="row">
                        <div class="border mb-3">re</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="border mb-3">
                <div class="row">
                        <div class="border mb-3">re</div>
                    </div>
                    <div class="row">
                        <div class="border mb-3">re</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="border mb-3 colspan-6">
                <button>Take the Rest</button>
            </div>
        </div>
    </div>    
</section>