<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid" id="navbar">
    <a class="navbar-brand" href="#"><img src="./assets/DA/logoOMARKET.png" width="200px" alt="logo OMarket"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 1){ echo "active";}?>" href="">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 2){ echo "active";}?>" href="article.php">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 4){ echo "active";}?>" href="about.php">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 3){ echo "active";}?>" href="form.php">Form</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <?php if ($page == 5){ echo "active";}?>" href="contact.php">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>