<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid" id="navbar">
    <div  id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link test" href="form.php">Take the test</a>
        </li>
        <li class="nav-item">
          <a class="nav-link product" href="article.php">Our Products</a>
        </li>
      </ul>
    </div>
    <div class="logo-container">
      <a class="navbar-brand" href="#"><img src="./assets/DA/logoOMARKET.png" width="200px" alt="logo OMarket"></a>
    </div>
    <div class="loginAndCart">
      <i class="fa-solid fa-cart-shopping fa-lg"></i>
      <i class="fa-solid fa-user fa-lg"> Log In</i>
    </div>
  </div>
</nav>