<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid" id="navbar">
    <a class="navbar-brand" href="#"><img src="./assets/DA/logoOMARKET.png" width="200px" alt="logo OMarket"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/OMarket-WebSite/" class="<?php echo ($page == "home" ? "active" : "")?>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/OMarket-WebSite/article.php" class="<?php echo ($page == "articles" ? "active" : "")?>">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/OMarket-WebSite/about.php" class="<?php echo ($page == "about" ? "active" : "")?>">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/OMarket-WebSite/form.php" class="<?php echo ($page == "form" ? "active" : "")?>">Form</a>
        </li>
      </ul>
    </div>
  </div>
</nav>